services:

  postgres:
    image: postgres:17
    container_name: f5-todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f5_todo
    ports:
      - "5433:5432"
    volumes:
      - f5_todo_postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/f5_todo?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network

volumes:
  f5_todo_postgres_data:

networks:
  todo-network:
    name: todo-network
    driver: bridge